[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.3.3",
    "plotly>=6.3.0",
    "requests>=2.32.5",
    "simple-salesforce>=1.12.9",
    "streamlit>=1.50.0",
    "supabase>=2.20.0",
]
